Walking skeleton
mrfishball/WebTTTClient pull request #1
Opened 2018-11-07 21:13 UTC by mrfishball

2018-11-07 22:32 UTC, cmvandrevala requested changes
I have a few small nitpicks/questions about this, but otherwise I really like this walking skeleton. Great job!

2018-11-07 22:32 UTC, cmvandrevala commented on .eslintrc
> +}
You don't have to include all of the eslint rules - just the ones that make sense for your project and your team. I am assuming these are the defaults, so they are fine for now.

2018-11-07 22:32 UTC, cmvandrevala commented on README.md
> +1. Fork this repository on GitHub.
Why do I need to fork this repo? Why not just clone it directly?

2018-11-07 22:32 UTC, cmvandrevala commented on package.json
> +    "start": "node server.js",
I like your scripts in package.json

2018-11-07 22:32 UTC, cmvandrevala commented on test/index_test.js
> +    expect(window.fetch).toHaveBeenCalledWith('https://live-ttt-rubyrails-api.herokuapp.com/v1/game')
Why is this production url hard-coded in your tests?

2018-11-08 15:06 UTC, mrfishball commented on .eslintrc
> +}
I want to have some rules in place to make sure the syntax is as readable and consistent as possible but, I didn't want to spend too much time on configuring the linter so I found a .eslintrc on GitHub and just went with it.

2018-11-08 15:07 UTC, mrfishball commented on README.md
> +1. Fork this repository on GitHub.
I suppose clone makes more sense. will change it to clone instead

2018-11-08 15:07 UTC, mrfishball commented on package.json
> +    "start": "node server.js",
:)

2018-11-08 16:08 UTC, mrfishball commented on test/index_test.js
> +    expect(window.fetch).toHaveBeenCalledWith('https://live-ttt-rubyrails-api.herokuapp.com/v1/game')
will fix that

2018-11-08 18:54 UTC, ericmeyer approved these changes

2018-11-08 18:58 UTC, merged